---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Action test/validation workflow
name: "Test GitHub Action ðŸ§ª"

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions: {}

jobs:
  ### Test the GitHub Action in this Repository ###
  tests:
    name: "Action Testing"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 5
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      # Perform setup prior to running test(s)
      - name: "Checkout sample project repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: "lfreleng-actions/test-python-project"
          path: "test-python-project"

      - name: "Setup Python"
        # yamllint disable-line rule:line-length
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version-file: "test-python-project/pyproject.toml"

      - name: "Build sample Python project"
        shell: bash
        run: |
          # Build sample Python project
          pip --disable-pip-version-check install build
          cd test-python-project
          python -m build

      - name: "Run Action: ${{ github.repository }}"
        uses: ./
        with:
          path: "test-python-project/dist"

      - name: "Run Action: ${{ github.repository }} [PATH PREFIX]"
        uses: ./
        with:
          path_prefix: "test-python-project"
          path: "dist"
